import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import { ThemeProvider, ThemeContext } from "../context/ThemeContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const { theme } = React.useContext(ThemeContext);
    console.log("theme", theme);

    return (
        <html lang="en">
            <ThemeProvider>
                <body data-theme="dark" className={inter.className}>
                    {children}
                </body>
            </ThemeProvider>
        </html>
    );
}
