import type { Metadata } from "next";
import React from "react";
import { ThemeProvider } from "../context/ThemeContext";
import Wrapper from "../components/Wrapper";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <ThemeProvider>
                <Wrapper>{children}</Wrapper>
            </ThemeProvider>
        </html>
    );
}
