import type { Metadata } from "next";
import React from "react";
import { ThemeProvider } from "../context/ThemeContext";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ThemeProvider>
            <html lang="en" suppressHydrationWarning>
                <body className={inter.className}>{children}</body>
            </html>
        </ThemeProvider>
    );
}
